// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/Lexer.flex

import compilerTools.Token;


@SuppressWarnings("fallthrough")
class Lexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\1\1\4\22\0\1\1"+
    "\1\5\1\6\2\0\1\7\1\0\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\21\11\22"+
    "\1\23\1\24\1\25\1\26\1\27\2\0\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\1\40\2\41"+
    "\1\42\1\43\1\44\1\45\1\46\1\41\1\47\1\50"+
    "\1\51\1\52\1\53\1\41\1\54\1\55\1\56\1\57"+
    "\1\0\1\60\1\0\1\41\1\0\1\61\1\62\1\63"+
    "\1\64\1\65\1\66\1\67\1\70\1\71\2\41\1\72"+
    "\1\73\1\74\1\75\1\76\1\41\1\77\1\100\1\101"+
    "\1\102\1\103\1\41\1\104\1\55\1\105\1\106\1\107"+
    "\1\110\7\0\1\3\73\0\1\111\7\0\1\111\3\0"+
    "\1\111\3\0\1\111\1\0\1\111\6\0\1\111\1\0"+
    "\1\111\4\0\1\111\7\0\1\111\3\0\1\111\3\0"+
    "\1\111\1\0\1\111\6\0\1\111\1\0\1\111\u012b\0"+
    "\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\2\16"+
    "\1\17\1\20\1\21\1\22\1\23\12\24\1\25\5\24"+
    "\1\26\1\27\1\30\16\24\1\31\1\1\1\32\1\33"+
    "\1\34\1\0\1\35\1\36\1\0\1\2\1\0\1\37"+
    "\1\40\1\41\12\24\1\42\3\24\1\42\20\24\1\43"+
    "\15\24\1\42\1\24\1\42\10\24\1\25\2\0\2\44"+
    "\75\24\1\0\1\2\2\24\1\42\45\24\1\45\24\24"+
    "\1\46\26\24\1\47\11\24\1\50\24\24";

  private static int [] zzUnpackAction() {
    int [] result = new int[309];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\112\0\112\0\224\0\336\0\u0128\0\112\0\112"+
    "\0\112\0\112\0\112\0\u0172\0\112\0\u01bc\0\112\0\u0206"+
    "\0\u0250\0\u029a\0\112\0\112\0\u02e4\0\u032e\0\u0378\0\u03c2"+
    "\0\u040c\0\u0456\0\u04a0\0\u04ea\0\u0534\0\u057e\0\u05c8\0\u0612"+
    "\0\u065c\0\u03c2\0\u06a6\0\u06f0\0\u073a\0\u0784\0\u07ce\0\u03c2"+
    "\0\112\0\112\0\u0818\0\u0862\0\u08ac\0\u08f6\0\u0940\0\u098a"+
    "\0\u09d4\0\u0a1e\0\u0a68\0\u0ab2\0\u0afc\0\u0b46\0\u0b90\0\u0bda"+
    "\0\112\0\u0c24\0\112\0\112\0\112\0\u0128\0\112\0\112"+
    "\0\u0c6e\0\u0cb8\0\u0d02\0\112\0\112\0\112\0\u0d4c\0\u0d96"+
    "\0\u0de0\0\u0e2a\0\u0e74\0\u0ebe\0\u0f08\0\u0f52\0\u0f9c\0\u0fe6"+
    "\0\u1030\0\u107a\0\u10c4\0\u110e\0\u1158\0\u11a2\0\u11ec\0\u1236"+
    "\0\u1280\0\u12ca\0\u1314\0\u135e\0\u13a8\0\u13f2\0\u143c\0\u1486"+
    "\0\u14d0\0\u151a\0\u1564\0\u15ae\0\u15f8\0\u03c2\0\u1642\0\u168c"+
    "\0\u16d6\0\u1720\0\u176a\0\u17b4\0\u17fe\0\u1848\0\u1892\0\u18dc"+
    "\0\u1926\0\u1970\0\u19ba\0\u1a04\0\u1a4e\0\u1a98\0\u1ae2\0\u1b2c"+
    "\0\u1b76\0\u1bc0\0\u1c0a\0\u1c54\0\u1c9e\0\u1ce8\0\112\0\u1d32"+
    "\0\u1d7c\0\112\0\u1dc6\0\u1e10\0\u1e5a\0\u1ea4\0\u1eee\0\u1f38"+
    "\0\u1f82\0\u1fcc\0\u2016\0\u2060\0\u20aa\0\u20f4\0\u213e\0\u2188"+
    "\0\u21d2\0\u221c\0\u2266\0\u22b0\0\u22fa\0\u2344\0\u238e\0\u23d8"+
    "\0\u2422\0\u246c\0\u24b6\0\u2500\0\u254a\0\u2594\0\u25de\0\u2628"+
    "\0\u2672\0\u26bc\0\u2706\0\u2750\0\u279a\0\u27e4\0\u282e\0\u2878"+
    "\0\u28c2\0\u290c\0\u2956\0\u29a0\0\u29ea\0\u2a34\0\u2a7e\0\u2ac8"+
    "\0\u2b12\0\u2b5c\0\u2ba6\0\u2bf0\0\u2c3a\0\u2c84\0\u2cce\0\u2d18"+
    "\0\u2d62\0\u2dac\0\u2df6\0\u2e40\0\u2e8a\0\u2ed4\0\u2f1e\0\u2f68"+
    "\0\u2fb2\0\u1d32\0\u2ffc\0\u3046\0\u03c2\0\u3090\0\u30da\0\u3124"+
    "\0\u316e\0\u31b8\0\u3202\0\u324c\0\u3296\0\u32e0\0\u332a\0\u3374"+
    "\0\u33be\0\u3408\0\u3452\0\u349c\0\u34e6\0\u3530\0\u357a\0\u35c4"+
    "\0\u360e\0\u3658\0\u36a2\0\u36ec\0\u3736\0\u3780\0\u37ca\0\u3814"+
    "\0\u385e\0\u38a8\0\u38f2\0\u393c\0\u3986\0\u39d0\0\u3a1a\0\u3a64"+
    "\0\u3aae\0\u3af8\0\u03c2\0\u3b42\0\u3b8c\0\u3bd6\0\u3c20\0\u3c6a"+
    "\0\u3cb4\0\u3cfe\0\u3d48\0\u3d92\0\u3ddc\0\u3e26\0\u3e70\0\u3eba"+
    "\0\u3f04\0\u3f4e\0\u3f98\0\u3fe2\0\u402c\0\u4076\0\u40c0\0\u03c2"+
    "\0\u410a\0\u4154\0\u419e\0\u41e8\0\u4232\0\u427c\0\u42c6\0\u4310"+
    "\0\u435a\0\u43a4\0\u43ee\0\u4438\0\u4482\0\u44cc\0\u4516\0\u4560"+
    "\0\u45aa\0\u45f4\0\u463e\0\u4688\0\u46d2\0\u471c\0\u03c2\0\u4766"+
    "\0\u47b0\0\u47fa\0\u4844\0\u488e\0\u48d8\0\u4922\0\u496c\0\u49b6"+
    "\0\u03c2\0\u4a00\0\u4a4a\0\u4a94\0\u4ade\0\u4b28\0\u4b72\0\u4bbc"+
    "\0\u4c06\0\u4c50\0\u4c9a\0\u4ce4\0\u4d2e\0\u4d78\0\u4dc2\0\u4e0c"+
    "\0\u4e56\0\u4ea0\0\u4eea\0\u4f34\0\u4f7e";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[309];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\30\1\36\1\37"+
    "\2\30\1\40\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\30\1\47\1\30\1\50\1\30\1\51\1\52\1\30"+
    "\1\53\1\54\1\55\1\56\1\57\1\30\1\60\1\61"+
    "\1\30\1\62\1\63\1\42\1\64\1\65\1\66\1\67"+
    "\1\30\1\70\2\30\1\71\1\72\1\73\1\30\114\0"+
    "\1\3\135\0\1\74\71\0\1\75\7\0\2\76\1\0"+
    "\2\76\5\0\27\76\2\0\25\76\20\0\1\77\113\0"+
    "\1\100\106\0\1\101\4\0\1\102\110\0\1\103\111\0"+
    "\1\103\1\0\2\22\115\0\1\104\111\0\1\105\111\0"+
    "\1\106\104\0\2\30\5\0\27\30\2\0\25\30\3\0"+
    "\1\30\21\0\2\30\5\0\15\30\1\107\11\30\2\0"+
    "\14\30\1\110\10\30\3\0\1\30\21\0\2\30\5\0"+
    "\1\111\11\30\1\112\2\30\1\113\11\30\2\0\1\114"+
    "\10\30\1\115\2\30\1\116\10\30\3\0\1\30\21\0"+
    "\2\30\5\0\4\30\1\117\22\30\2\0\4\30\1\120"+
    "\20\30\3\0\1\30\21\0\2\30\5\0\14\30\1\121"+
    "\3\30\1\122\2\30\1\123\1\124\2\30\2\0\13\30"+
    "\1\125\3\30\1\126\2\30\1\127\1\130\1\30\3\0"+
    "\1\30\21\0\2\30\5\0\1\131\7\30\1\132\1\30"+
    "\1\133\14\30\2\0\1\134\13\30\1\135\10\30\3\0"+
    "\1\30\21\0\2\30\5\0\4\30\1\136\22\30\2\0"+
    "\4\30\1\137\20\30\3\0\1\30\21\0\2\30\5\0"+
    "\13\30\1\140\1\141\12\30\2\0\12\30\1\142\1\143"+
    "\11\30\3\0\1\30\21\0\2\30\5\0\10\30\1\144"+
    "\16\30\2\0\10\30\1\145\14\30\3\0\1\30\21\0"+
    "\2\30\5\0\15\30\1\146\11\30\2\0\14\30\1\146"+
    "\10\30\3\0\1\30\21\0\2\30\5\0\1\147\16\30"+
    "\1\150\2\30\1\151\4\30\2\0\1\152\15\30\1\153"+
    "\2\30\1\154\3\30\3\0\1\30\21\0\2\30\5\0"+
    "\1\155\3\30\1\156\10\30\1\157\11\30\2\0\1\160"+
    "\3\30\1\161\7\30\1\162\10\30\3\0\1\30\21\0"+
    "\2\30\5\0\1\163\7\30\1\164\16\30\2\0\1\165"+
    "\7\30\1\166\14\30\3\0\1\30\21\0\2\30\5\0"+
    "\4\30\1\167\22\30\2\0\4\30\1\170\20\30\3\0"+
    "\1\30\21\0\2\30\5\0\1\171\3\30\1\172\22\30"+
    "\2\0\1\173\3\30\1\174\20\30\3\0\1\30\21\0"+
    "\2\30\5\0\27\30\2\0\14\30\1\110\10\30\3\0"+
    "\1\30\21\0\2\30\5\0\27\30\2\0\1\114\10\30"+
    "\1\115\2\30\1\116\10\30\3\0\1\30\21\0\2\30"+
    "\5\0\27\30\2\0\4\30\1\120\20\30\3\0\1\30"+
    "\21\0\2\30\5\0\27\30\2\0\13\30\1\125\3\30"+
    "\1\126\2\30\1\127\1\130\1\30\3\0\1\30\21\0"+
    "\2\30\5\0\27\30\2\0\1\134\7\30\1\175\3\30"+
    "\1\176\10\30\3\0\1\30\21\0\2\30\5\0\27\30"+
    "\2\0\4\30\1\137\20\30\3\0\1\30\21\0\2\30"+
    "\5\0\27\30\2\0\12\30\1\142\1\143\11\30\3\0"+
    "\1\30\21\0\2\30\5\0\27\30\2\0\10\30\1\145"+
    "\14\30\3\0\1\30\21\0\2\30\5\0\27\30\2\0"+
    "\14\30\1\146\10\30\3\0\1\30\21\0\2\30\5\0"+
    "\27\30\2\0\1\152\15\30\1\153\2\30\1\154\3\30"+
    "\3\0\1\30\21\0\2\30\5\0\27\30\2\0\1\160"+
    "\3\30\1\161\7\30\1\162\10\30\3\0\1\30\21\0"+
    "\2\30\5\0\27\30\2\0\1\165\7\30\1\166\14\30"+
    "\3\0\1\30\21\0\2\30\5\0\27\30\2\0\4\30"+
    "\1\170\20\30\3\0\1\30\21\0\2\30\5\0\27\30"+
    "\2\0\1\173\3\30\1\174\20\30\3\0\1\30\107\0"+
    "\1\177\2\0\13\200\1\201\76\200\2\102\1\3\1\102"+
    "\1\4\105\102\21\0\1\202\1\203\110\0\2\30\5\0"+
    "\12\30\1\204\14\30\2\0\25\30\3\0\1\30\21\0"+
    "\2\30\5\0\27\30\2\0\14\30\1\205\10\30\3\0"+
    "\1\30\21\0\2\30\5\0\20\30\1\206\6\30\2\0"+
    "\25\30\3\0\1\30\21\0\2\30\5\0\1\207\26\30"+
    "\2\0\25\30\3\0\1\30\21\0\2\30\5\0\13\30"+
    "\1\210\13\30\2\0\25\30\3\0\1\30\21\0\2\30"+
    "\5\0\27\30\2\0\17\30\1\211\5\30\3\0\1\30"+
    "\21\0\2\30\5\0\27\30\2\0\1\212\24\30\3\0"+
    "\1\30\21\0\2\30\5\0\27\30\2\0\12\30\1\213"+
    "\12\30\3\0\1\30\21\0\2\30\5\0\2\30\1\214"+
    "\24\30\2\0\25\30\3\0\1\30\21\0\2\30\5\0"+
    "\27\30\2\0\2\30\1\215\22\30\3\0\1\30\21\0"+
    "\2\30\5\0\21\30\1\216\5\30\2\0\25\30\3\0"+
    "\1\30\21\0\2\30\5\0\21\30\1\217\5\30\2\0"+
    "\25\30\3\0\1\30\21\0\2\30\5\0\1\220\26\30"+
    "\2\0\25\30\3\0\1\30\21\0\2\30\5\0\2\30"+
    "\1\221\24\30\2\0\25\30\3\0\1\30\21\0\2\30"+
    "\5\0\27\30\2\0\20\30\1\222\4\30\3\0\1\30"+
    "\21\0\2\30\5\0\27\30\2\0\20\30\1\223\4\30"+
    "\3\0\1\30\21\0\2\30\5\0\27\30\2\0\1\224"+
    "\24\30\3\0\1\30\21\0\2\30\5\0\27\30\2\0"+
    "\2\30\1\225\22\30\3\0\1\30\21\0\2\30\5\0"+
    "\12\30\1\111\14\30\2\0\25\30\3\0\1\30\21\0"+
    "\2\30\5\0\14\30\1\226\12\30\2\0\25\30\3\0"+
    "\1\30\21\0\2\30\5\0\15\30\1\227\11\30\2\0"+
    "\25\30\3\0\1\30\21\0\2\30\5\0\27\30\2\0"+
    "\11\30\1\114\13\30\3\0\1\30\21\0\2\30\5\0"+
    "\27\30\2\0\20\30\1\230\4\30\3\0\1\30\21\0"+
    "\2\30\5\0\17\30\1\231\7\30\2\0\25\30\3\0"+
    "\1\30\21\0\2\30\5\0\27\30\2\0\16\30\1\232"+
    "\6\30\3\0\1\30\21\0\2\30\5\0\16\30\1\233"+
    "\10\30\2\0\25\30\3\0\1\30\21\0\2\30\5\0"+
    "\10\30\1\234\10\30\1\235\5\30\2\0\25\30\3\0"+
    "\1\30\21\0\2\30\5\0\27\30\2\0\15\30\1\236"+
    "\7\30\3\0\1\30\21\0\2\30\5\0\27\30\2\0"+
    "\10\30\1\237\7\30\1\240\4\30\3\0\1\30\21\0"+
    "\2\30\5\0\4\30\1\241\13\30\1\242\6\30\2\0"+
    "\25\30\3\0\1\30\21\0\2\30\5\0\27\30\2\0"+
    "\4\30\1\243\12\30\1\244\5\30\3\0\1\30\21\0"+
    "\2\30\5\0\17\30\1\245\7\30\2\0\25\30\3\0"+
    "\1\30\21\0\2\30\5\0\10\30\1\246\16\30\2\0"+
    "\25\30\3\0\1\30\21\0\2\30\5\0\1\30\1\247"+
    "\25\30\2\0\25\30\3\0\1\30\21\0\2\30\5\0"+
    "\27\30\2\0\16\30\1\250\6\30\3\0\1\30\21\0"+
    "\2\30\5\0\27\30\2\0\10\30\1\251\14\30\3\0"+
    "\1\30\21\0\2\30\5\0\27\30\2\0\1\30\1\252"+
    "\23\30\3\0\1\30\21\0\2\30\5\0\10\30\1\253"+
    "\3\30\1\254\12\30\2\0\25\30\3\0\1\30\21\0"+
    "\2\30\5\0\1\255\20\30\1\256\5\30\2\0\25\30"+
    "\3\0\1\30\21\0\2\30\5\0\13\30\1\257\13\30"+
    "\2\0\25\30\3\0\1\30\21\0\2\30\5\0\27\30"+
    "\2\0\10\30\1\260\2\30\1\261\11\30\3\0\1\30"+
    "\21\0\2\30\5\0\27\30\2\0\1\262\17\30\1\263"+
    "\4\30\3\0\1\30\21\0\2\30\5\0\27\30\2\0"+
    "\12\30\1\264\12\30\3\0\1\30\21\0\2\30\5\0"+
    "\12\30\1\265\14\30\2\0\25\30\3\0\1\30\21\0"+
    "\2\30\5\0\6\30\1\266\5\30\1\206\12\30\2\0"+
    "\25\30\3\0\1\30\21\0\2\30\5\0\27\30\2\0"+
    "\11\30\1\267\13\30\3\0\1\30\21\0\2\30\5\0"+
    "\27\30\2\0\6\30\1\270\4\30\1\211\11\30\3\0"+
    "\1\30\21\0\2\30\5\0\24\30\1\271\2\30\2\0"+
    "\25\30\3\0\1\30\21\0\2\30\5\0\27\30\2\0"+
    "\23\30\1\272\1\30\3\0\1\30\21\0\2\30\5\0"+
    "\2\30\1\273\24\30\2\0\25\30\3\0\1\30\21\0"+
    "\2\30\5\0\17\30\1\274\7\30\2\0\25\30\3\0"+
    "\1\30\21\0\2\30\5\0\27\30\2\0\2\30\1\275"+
    "\22\30\3\0\1\30\21\0\2\30\5\0\27\30\2\0"+
    "\16\30\1\276\6\30\3\0\1\30\21\0\2\30\5\0"+
    "\27\30\2\0\13\30\1\277\11\30\3\0\1\30\21\0"+
    "\2\30\5\0\27\30\2\0\20\30\1\300\4\30\3\0"+
    "\1\30\13\200\1\301\111\200\1\301\4\200\1\302\71\200"+
    "\21\0\2\203\110\0\2\30\5\0\4\30\1\303\22\30"+
    "\2\0\25\30\3\0\1\30\21\0\2\30\5\0\27\30"+
    "\2\0\11\30\1\304\13\30\3\0\1\30\21\0\2\30"+
    "\5\0\15\30\1\305\11\30\2\0\25\30\3\0\1\30"+
    "\21\0\2\30\5\0\20\30\1\306\6\30\2\0\25\30"+
    "\3\0\1\30\21\0\2\30\5\0\22\30\1\307\4\30"+
    "\2\0\25\30\3\0\1\30\21\0\2\30\5\0\27\30"+
    "\2\0\14\30\1\305\10\30\3\0\1\30\21\0\2\30"+
    "\5\0\27\30\2\0\17\30\1\310\5\30\3\0\1\30"+
    "\21\0\2\30\5\0\27\30\2\0\21\30\1\311\3\30"+
    "\3\0\1\30\21\0\2\30\5\0\10\30\1\312\16\30"+
    "\2\0\25\30\3\0\1\30\21\0\2\30\5\0\27\30"+
    "\2\0\10\30\1\313\14\30\3\0\1\30\21\0\2\30"+
    "\5\0\4\30\1\314\12\30\1\315\7\30\2\0\25\30"+
    "\3\0\1\30\21\0\2\30\5\0\1\316\26\30\2\0"+
    "\25\30\3\0\1\30\21\0\2\30\5\0\12\30\1\317"+
    "\14\30\2\0\25\30\3\0\1\30\21\0\2\30\5\0"+
    "\4\30\1\320\22\30\2\0\25\30\3\0\1\30\21\0"+
    "\2\30\5\0\27\30\2\0\4\30\1\321\11\30\1\322"+
    "\6\30\3\0\1\30\21\0\2\30\5\0\27\30\2\0"+
    "\1\323\24\30\3\0\1\30\21\0\2\30\5\0\27\30"+
    "\2\0\11\30\1\324\13\30\3\0\1\30\21\0\2\30"+
    "\5\0\27\30\2\0\4\30\1\325\20\30\3\0\1\30"+
    "\21\0\2\30\5\0\1\326\26\30\2\0\25\30\3\0"+
    "\1\30\21\0\2\30\5\0\21\30\1\327\5\30\2\0"+
    "\25\30\3\0\1\30\21\0\2\30\5\0\27\30\2\0"+
    "\1\330\24\30\3\0\1\30\21\0\2\30\5\0\4\30"+
    "\1\331\22\30\2\0\25\30\3\0\1\30\21\0\2\30"+
    "\5\0\27\30\2\0\4\30\1\332\20\30\3\0\1\30"+
    "\21\0\2\30\5\0\15\30\1\333\1\30\1\334\7\30"+
    "\2\0\25\30\3\0\1\30\21\0\2\30\5\0\2\30"+
    "\1\335\24\30\2\0\25\30\3\0\1\30\21\0\2\30"+
    "\5\0\4\30\1\336\22\30\2\0\25\30\3\0\1\30"+
    "\21\0\2\30\5\0\27\30\2\0\14\30\1\337\1\30"+
    "\1\340\6\30\3\0\1\30\21\0\2\30\5\0\27\30"+
    "\2\0\2\30\1\341\22\30\3\0\1\30\21\0\2\30"+
    "\5\0\27\30\2\0\4\30\1\342\20\30\3\0\1\30"+
    "\21\0\2\30\5\0\14\30\1\343\12\30\2\0\25\30"+
    "\3\0\1\30\21\0\2\30\5\0\13\30\1\206\13\30"+
    "\2\0\25\30\3\0\1\30\21\0\2\30\5\0\27\30"+
    "\2\0\13\30\1\344\11\30\3\0\1\30\21\0\2\30"+
    "\5\0\27\30\2\0\12\30\1\211\12\30\3\0\1\30"+
    "\21\0\2\30\5\0\1\305\26\30\2\0\25\30\3\0"+
    "\1\30\21\0\2\30\5\0\14\30\1\345\6\30\1\346"+
    "\3\30\2\0\25\30\3\0\1\30\21\0\2\30\5\0"+
    "\12\30\1\347\14\30\2\0\25\30\3\0\1\30\21\0"+
    "\2\30\5\0\27\30\2\0\1\305\24\30\3\0\1\30"+
    "\21\0\2\30\5\0\27\30\2\0\13\30\1\350\6\30"+
    "\1\351\2\30\3\0\1\30\21\0\2\30\5\0\27\30"+
    "\2\0\11\30\1\352\13\30\3\0\1\30\21\0\2\30"+
    "\5\0\26\30\1\353\2\0\25\30\3\0\1\30\21\0"+
    "\2\30\5\0\6\30\1\206\20\30\2\0\25\30\3\0"+
    "\1\30\21\0\2\30\5\0\12\30\1\305\14\30\2\0"+
    "\25\30\3\0\1\30\21\0\2\30\5\0\15\30\1\354"+
    "\11\30\2\0\25\30\3\0\1\30\21\0\2\30\5\0"+
    "\16\30\1\355\10\30\2\0\25\30\3\0\1\30\21\0"+
    "\2\30\5\0\27\30\2\0\24\30\1\353\3\0\1\30"+
    "\21\0\2\30\5\0\27\30\2\0\6\30\1\211\16\30"+
    "\3\0\1\30\21\0\2\30\5\0\27\30\2\0\11\30"+
    "\1\305\13\30\3\0\1\30\21\0\2\30\5\0\27\30"+
    "\2\0\14\30\1\356\10\30\3\0\1\30\21\0\2\30"+
    "\5\0\27\30\2\0\15\30\1\357\7\30\3\0\1\30"+
    "\21\0\2\30\5\0\10\30\1\331\16\30\2\0\25\30"+
    "\3\0\1\30\21\0\2\30\5\0\22\30\1\360\4\30"+
    "\2\0\25\30\3\0\1\30\21\0\2\30\5\0\27\30"+
    "\2\0\10\30\1\332\14\30\3\0\1\30\21\0\2\30"+
    "\5\0\27\30\2\0\21\30\1\361\3\30\3\0\1\30"+
    "\21\0\2\30\5\0\21\30\1\362\5\30\2\0\25\30"+
    "\3\0\1\30\21\0\2\30\5\0\27\30\2\0\20\30"+
    "\1\363\4\30\3\0\1\30\21\0\2\30\5\0\10\30"+
    "\1\206\16\30\2\0\25\30\3\0\1\30\21\0\2\30"+
    "\5\0\3\30\1\364\23\30\2\0\25\30\3\0\1\30"+
    "\21\0\2\30\5\0\27\30\2\0\10\30\1\211\14\30"+
    "\3\0\1\30\21\0\2\30\5\0\27\30\2\0\3\30"+
    "\1\365\21\30\3\0\1\30\21\0\2\30\5\0\27\30"+
    "\2\0\1\366\24\30\3\0\1\30\21\0\2\30\5\0"+
    "\27\30\2\0\1\367\24\30\3\0\1\30\13\200\1\301"+
    "\4\200\1\3\71\200\21\0\2\30\5\0\1\370\26\30"+
    "\2\0\25\30\3\0\1\30\21\0\2\30\5\0\27\30"+
    "\2\0\4\30\1\371\20\30\3\0\1\30\21\0\2\30"+
    "\5\0\4\30\1\305\22\30\2\0\25\30\3\0\1\30"+
    "\21\0\2\30\5\0\14\30\1\305\12\30\2\0\25\30"+
    "\3\0\1\30\21\0\2\30\5\0\27\30\2\0\4\30"+
    "\1\305\20\30\3\0\1\30\21\0\2\30\5\0\27\30"+
    "\2\0\13\30\1\305\11\30\3\0\1\30\21\0\2\30"+
    "\5\0\13\30\1\372\13\30\2\0\25\30\3\0\1\30"+
    "\21\0\2\30\5\0\27\30\2\0\12\30\1\373\12\30"+
    "\3\0\1\30\21\0\2\30\5\0\17\30\1\362\7\30"+
    "\2\0\25\30\3\0\1\30\21\0\2\30\5\0\1\331"+
    "\26\30\2\0\25\30\3\0\1\30\21\0\2\30\5\0"+
    "\21\30\1\347\5\30\2\0\25\30\3\0\1\30\21\0"+
    "\2\30\5\0\22\30\1\374\4\30\2\0\25\30\3\0"+
    "\1\30\21\0\2\30\5\0\16\30\1\375\10\30\2\0"+
    "\25\30\3\0\1\30\21\0\2\30\5\0\27\30\2\0"+
    "\16\30\1\363\6\30\3\0\1\30\21\0\2\30\5\0"+
    "\27\30\2\0\1\332\24\30\3\0\1\30\21\0\2\30"+
    "\5\0\27\30\2\0\20\30\1\352\4\30\3\0\1\30"+
    "\21\0\2\30\5\0\27\30\2\0\21\30\1\376\3\30"+
    "\3\0\1\30\21\0\2\30\5\0\27\30\2\0\15\30"+
    "\1\377\7\30\3\0\1\30\21\0\2\30\5\0\12\30"+
    "\1\u0100\14\30\2\0\25\30\3\0\1\30\21\0\2\30"+
    "\5\0\1\u0101\26\30\2\0\25\30\3\0\1\30\21\0"+
    "\2\30\5\0\27\30\2\0\13\30\1\u0102\11\30\3\0"+
    "\1\30\21\0\2\30\5\0\3\30\1\245\23\30\2\0"+
    "\25\30\3\0\1\30\21\0\2\30\5\0\27\30\2\0"+
    "\3\30\1\250\21\30\3\0\1\30\21\0\2\30\5\0"+
    "\17\30\1\u0103\7\30\2\0\25\30\3\0\1\30\21\0"+
    "\2\30\5\0\10\30\1\u0104\16\30\2\0\25\30\3\0"+
    "\1\30\21\0\2\30\5\0\10\30\1\u0105\16\30\2\0"+
    "\25\30\3\0\1\30\21\0\2\30\5\0\14\30\1\u0103"+
    "\12\30\2\0\25\30\3\0\1\30\21\0\2\30\5\0"+
    "\27\30\2\0\16\30\1\u0106\6\30\3\0\1\30\21\0"+
    "\2\30\5\0\27\30\2\0\10\30\1\u0107\14\30\3\0"+
    "\1\30\21\0\2\30\5\0\27\30\2\0\10\30\1\u0108"+
    "\14\30\3\0\1\30\21\0\2\30\5\0\27\30\2\0"+
    "\13\30\1\u0106\11\30\3\0\1\30\21\0\2\30\5\0"+
    "\21\30\1\u0109\5\30\2\0\25\30\3\0\1\30\21\0"+
    "\2\30\5\0\27\30\2\0\20\30\1\u010a\4\30\3\0"+
    "\1\30\21\0\2\30\5\0\2\30\1\u010b\24\30\2\0"+
    "\25\30\3\0\1\30\21\0\2\30\5\0\1\u010c\26\30"+
    "\2\0\25\30\3\0\1\30\21\0\2\30\5\0\10\30"+
    "\1\u010d\16\30\2\0\25\30\3\0\1\30\21\0\2\30"+
    "\5\0\27\30\2\0\2\30\1\u010e\22\30\3\0\1\30"+
    "\21\0\2\30\5\0\27\30\2\0\1\u010f\24\30\3\0"+
    "\1\30\21\0\2\30\5\0\27\30\2\0\10\30\1\u0110"+
    "\14\30\3\0\1\30\21\0\2\30\5\0\17\30\1\u0111"+
    "\7\30\2\0\25\30\3\0\1\30\21\0\2\30\5\0"+
    "\4\30\1\u0112\22\30\2\0\25\30\3\0\1\30\21\0"+
    "\2\30\5\0\27\30\2\0\16\30\1\u0113\6\30\3\0"+
    "\1\30\21\0\2\30\5\0\27\30\2\0\4\30\1\u0114"+
    "\20\30\3\0\1\30\21\0\2\30\5\0\10\30\1\u0115"+
    "\16\30\2\0\25\30\3\0\1\30\21\0\2\30\5\0"+
    "\27\30\2\0\10\30\1\u0116\14\30\3\0\1\30\21\0"+
    "\2\30\5\0\15\30\1\u0117\11\30\2\0\25\30\3\0"+
    "\1\30\21\0\2\30\5\0\27\30\2\0\14\30\1\u0117"+
    "\10\30\3\0\1\30\21\0\2\30\5\0\1\u0118\26\30"+
    "\2\0\25\30\3\0\1\30\21\0\2\30\5\0\27\30"+
    "\2\0\1\u0119\24\30\3\0\1\30\21\0\2\30\5\0"+
    "\27\30\2\0\11\30\1\u0100\13\30\3\0\1\30\21\0"+
    "\2\30\5\0\27\30\2\0\13\30\1\u011a\11\30\3\0"+
    "\1\30\21\0\2\30\5\0\14\30\1\362\12\30\2\0"+
    "\25\30\3\0\1\30\21\0\2\30\5\0\27\30\2\0"+
    "\1\u011b\24\30\3\0\1\30\21\0\2\30\5\0\1\u011c"+
    "\26\30\2\0\25\30\3\0\1\30\21\0\2\30\5\0"+
    "\27\30\2\0\1\u011d\24\30\3\0\1\30\21\0\2\30"+
    "\5\0\1\u0112\26\30\2\0\25\30\3\0\1\30\21\0"+
    "\2\30\5\0\21\30\1\206\5\30\2\0\25\30\3\0"+
    "\1\30\21\0\2\30\5\0\27\30\2\0\1\u0114\24\30"+
    "\3\0\1\30\21\0\2\30\5\0\27\30\2\0\20\30"+
    "\1\211\4\30\3\0\1\30\21\0\2\30\5\0\14\30"+
    "\1\u011e\12\30\2\0\25\30\3\0\1\30\21\0\2\30"+
    "\5\0\27\30\2\0\20\30\1\u011f\4\30\3\0\1\30"+
    "\21\0\2\30\5\0\21\30\1\374\5\30\2\0\25\30"+
    "\3\0\1\30\21\0\2\30\5\0\13\30\1\u0120\13\30"+
    "\2\0\25\30\3\0\1\30\21\0\2\30\5\0\15\30"+
    "\1\u0121\11\30\2\0\25\30\3\0\1\30\21\0\2\30"+
    "\5\0\27\30\2\0\20\30\1\376\4\30\3\0\1\30"+
    "\21\0\2\30\5\0\27\30\2\0\12\30\1\u0122\12\30"+
    "\3\0\1\30\21\0\2\30\5\0\27\30\2\0\14\30"+
    "\1\u0121\10\30\3\0\1\30\21\0\2\30\5\0\17\30"+
    "\1\u0123\7\30\2\0\25\30\3\0\1\30\21\0\2\30"+
    "\5\0\27\30\2\0\16\30\1\u0124\6\30\3\0\1\30"+
    "\21\0\2\30\5\0\10\30\1\u0125\16\30\2\0\25\30"+
    "\3\0\1\30\21\0\2\30\5\0\3\30\1\206\23\30"+
    "\2\0\25\30\3\0\1\30\21\0\2\30\5\0\2\30"+
    "\1\206\24\30\2\0\25\30\3\0\1\30\21\0\2\30"+
    "\5\0\27\30\2\0\10\30\1\u0126\14\30\3\0\1\30"+
    "\21\0\2\30\5\0\27\30\2\0\3\30\1\211\21\30"+
    "\3\0\1\30\21\0\2\30\5\0\27\30\2\0\2\30"+
    "\1\211\22\30\3\0\1\30\21\0\2\30\5\0\14\30"+
    "\1\374\12\30\2\0\25\30\3\0\1\30\21\0\2\30"+
    "\5\0\17\30\1\305\7\30\2\0\25\30\3\0\1\30"+
    "\21\0\2\30\5\0\27\30\2\0\13\30\1\376\11\30"+
    "\3\0\1\30\21\0\2\30\5\0\27\30\2\0\16\30"+
    "\1\305\6\30\3\0\1\30\21\0\2\30\5\0\4\30"+
    "\1\u0127\22\30\2\0\25\30\3\0\1\30\21\0\2\30"+
    "\5\0\27\30\2\0\4\30\1\u0128\20\30\3\0\1\30"+
    "\21\0\2\30\5\0\3\30\1\u0129\23\30\2\0\25\30"+
    "\3\0\1\30\21\0\2\30\5\0\27\30\2\0\3\30"+
    "\1\u012a\21\30\3\0\1\30\21\0\2\30\5\0\27\30"+
    "\2\0\20\30\1\u012b\4\30\3\0\1\30\21\0\2\30"+
    "\5\0\27\30\2\0\13\30\1\363\11\30\3\0\1\30"+
    "\21\0\2\30\5\0\12\30\1\u0117\14\30\2\0\25\30"+
    "\3\0\1\30\21\0\2\30\5\0\27\30\2\0\11\30"+
    "\1\u0117\13\30\3\0\1\30\21\0\2\30\5\0\21\30"+
    "\1\u012c\5\30\2\0\25\30\3\0\1\30\21\0\2\30"+
    "\5\0\27\30\2\0\4\30\1\u012d\20\30\3\0\1\30"+
    "\21\0\2\30\5\0\10\30\1\u0112\16\30\2\0\25\30"+
    "\3\0\1\30\21\0\2\30\5\0\27\30\2\0\10\30"+
    "\1\u0114\14\30\3\0\1\30\21\0\2\30\5\0\1\u012e"+
    "\26\30\2\0\25\30\3\0\1\30\21\0\2\30\5\0"+
    "\27\30\2\0\1\u012f\24\30\3\0\1\30\21\0\2\30"+
    "\5\0\16\30\1\u0130\10\30\2\0\25\30\3\0\1\30"+
    "\21\0\2\30\5\0\27\30\2\0\15\30\1\u0131\7\30"+
    "\3\0\1\30\21\0\2\30\5\0\14\30\1\u0132\12\30"+
    "\2\0\25\30\3\0\1\30\21\0\2\30\5\0\27\30"+
    "\2\0\13\30\1\u0133\11\30\3\0\1\30\21\0\2\30"+
    "\5\0\4\30\1\u0134\22\30\2\0\25\30\3\0\1\30"+
    "\21\0\2\30\5\0\27\30\2\0\4\30\1\u0135\20\30"+
    "\3\0\1\30\21\0\2\30\5\0\27\30\2\0\4\30"+
    "\1\u0117\20\30\3\0\1\30\21\0\2\30\5\0\4\30"+
    "\1\u0117\22\30\2\0\25\30\3\0\1\30\21\0\2\30"+
    "\5\0\27\30\2\0\20\30\1\u0117\4\30\3\0\1\30"+
    "\21\0\2\30\5\0\20\30\1\305\6\30\2\0\25\30"+
    "\3\0\1\30\21\0\2\30\5\0\27\30\2\0\17\30"+
    "\1\305\5\30\3\0\1\30\21\0\2\30\5\0\1\255"+
    "\26\30\2\0\25\30\3\0\1\30\21\0\2\30\5\0"+
    "\27\30\2\0\1\262\24\30\3\0\1\30\21\0\2\30"+
    "\5\0\21\30\1\306\5\30\2\0\25\30\3\0\1\30"+
    "\21\0\2\30\5\0\27\30\2\0\20\30\1\310\4\30"+
    "\3\0\1\30\21\0\2\30\5\0\17\30\1\206\7\30"+
    "\2\0\25\30\3\0\1\30\21\0\2\30\5\0\27\30"+
    "\2\0\16\30\1\211\6\30\3\0\1\30";

  private static int [] zzUnpacktrans() {
    int [] result = new int[20424];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\3\1\5\11\1\1\1\11\1\1\1\11"+
    "\3\1\2\11\24\1\2\11\16\1\1\11\1\1\3\11"+
    "\1\0\2\11\1\0\1\1\1\0\3\11\70\1\1\11"+
    "\2\0\1\11\76\1\1\0\164\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[309];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    private Token token(String lexeme, String lexicalComp, int line, int column){
        return new Token(lexeme, lexicalComp, line+1, column+1);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return token(yytext(), "ERROR", yyline, yycolumn);
            }
          // fall through
          case 41: break;
          case 2:
            { /*Ignorar*/
            }
          // fall through
          case 42: break;
          case 3:
            { return token(yytext(), "COMILLADOBLE", yyline, yycolumn);
            }
          // fall through
          case 43: break;
          case 4:
            { return token(yytext(), "MODULO", yyline, yycolumn);
            }
          // fall through
          case 44: break;
          case 5:
            { return token(yytext(), "COMILLASIMPLE", yyline, yycolumn);
            }
          // fall through
          case 45: break;
          case 6:
            { return token(yytext(), "PARENTESISABIERTO", yyline, yycolumn);
            }
          // fall through
          case 46: break;
          case 7:
            { return token(yytext(), "PARENTESISCERRADO", yyline, yycolumn);
            }
          // fall through
          case 47: break;
          case 8:
            { return token(yytext(), "MULTIPLICACION", yyline, yycolumn);
            }
          // fall through
          case 48: break;
          case 9:
            { return token(yytext(), "SUMA", yyline, yycolumn);
            }
          // fall through
          case 49: break;
          case 10:
            { return token(yytext(), "COMA", yyline, yycolumn);
            }
          // fall through
          case 50: break;
          case 11:
            { return token(yytext(), "RESTA", yyline, yycolumn);
            }
          // fall through
          case 51: break;
          case 12:
            { return token(yytext(), "PUNTO", yyline, yycolumn);
            }
          // fall through
          case 52: break;
          case 13:
            { return token(yytext(), "DIVISION", yyline, yycolumn);
            }
          // fall through
          case 53: break;
          case 14:
            { return token(yytext(), "NUMERO", yyline, yycolumn);
            }
          // fall through
          case 54: break;
          case 15:
            { return token(yytext(), "DOSPUNTOS", yyline, yycolumn);
            }
          // fall through
          case 55: break;
          case 16:
            { return token(yytext(), "PUNTOCOMA", yyline, yycolumn);
            }
          // fall through
          case 56: break;
          case 17:
            { return token(yytext(), "MENORQUE", yyline, yycolumn);
            }
          // fall through
          case 57: break;
          case 18:
            { return token(yytext(), "ASIGNACION", yyline, yycolumn);
            }
          // fall through
          case 58: break;
          case 19:
            { return token(yytext(), "MAYORQUE", yyline, yycolumn);
            }
          // fall through
          case 59: break;
          case 20:
            { return token(yytext(), "ID", yyline, yycolumn);
            }
          // fall through
          case 60: break;
          case 21:
            { return token(yytext(), "O", yyline, yycolumn);
            }
          // fall through
          case 61: break;
          case 22:
            { return token(yytext(), "Y", yyline, yycolumn);
            }
          // fall through
          case 62: break;
          case 23:
            { return token(yytext(), "CORCHETEABIERTO", yyline, yycolumn);
            }
          // fall through
          case 63: break;
          case 24:
            { return token(yytext(), "CORCHETECERRADO", yyline, yycolumn);
            }
          // fall through
          case 64: break;
          case 25:
            { return token(yytext(), "LLAVEABIERTO", yyline, yycolumn);
            }
          // fall through
          case 65: break;
          case 26:
            { return token(yytext(), "LLAVECERRADO", yyline, yycolumn);
            }
          // fall through
          case 66: break;
          case 27:
            { return token(yytext(), "DIFERENTE", yyline, yycolumn);
            }
          // fall through
          case 67: break;
          case 28:
            { return token(yytext(), "CADENA", yyline, yycolumn);
            }
          // fall through
          case 68: break;
          case 29:
            { return token(yytext(), "INCREMENTO", yyline, yycolumn);
            }
          // fall through
          case 69: break;
          case 30:
            { return token(yytext(), "DECREMENTO", yyline, yycolumn);
            }
          // fall through
          case 70: break;
          case 31:
            { return token(yytext(), "MENORIGUALQUE", yyline, yycolumn);
            }
          // fall through
          case 71: break;
          case 32:
            { return token(yytext(), "IGUAL", yyline, yycolumn);
            }
          // fall through
          case 72: break;
          case 33:
            { return token(yytext(), "MAYORIGUALQUE", yyline, yycolumn);
            }
          // fall through
          case 73: break;
          case 34:
            { return token(yytext(), "RESERVADA", yyline, yycolumn);
            }
          // fall through
          case 74: break;
          case 35:
            { return token(yytext(), "NO", yyline, yycolumn);
            }
          // fall through
          case 75: break;
          case 36:
            { return token(yytext(), "REAL", yyline, yycolumn);
            }
          // fall through
          case 76: break;
          case 37:
            { return token(yytext(), "RAIZ", yyline, yycolumn);
            }
          // fall through
          case 77: break;
          case 38:
            { return token(yytext(), "FINAL", yyline, yycolumn);
            }
          // fall through
          case 78: break;
          case 39:
            { return token(yytext(), "TIPODEDATO", yyline, yycolumn);
            }
          // fall through
          case 79: break;
          case 40:
            { return token(yytext(), "INICIO", yyline, yycolumn);
            }
          // fall through
          case 80: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
